---
# role: samba_ad_member
# file: handlers/main.yml

- name: SAMBA_AD_MEMBER | Synchronize the configured machine keytab
  become: true
  become_user: root
  ansible.builtin.command:
    argv: [net, ads, keytab, create, --machine-pass]
  changed_when: true
  listen: synchronize machine keytab

- name: SAMBA_AD_MEMBER | Restart winbind
  become: true
  become_user: root
  ansible.builtin.systemd_service:
    name: "{{ __samba_ad_member_winbind_service }}"
    enabled: true
    masked: false
    state: restarted
  listen: restart winbind

- name: SAMBA_AD_MEMBER | Restart Samba
  become: true
  become_user: root
  ansible.builtin.systemd_service:
    name: "{{ __samba_ad_member_smb_service }}"
    enabled: true
    masked: false
    state: restarted
  listen: restart samba

- name: SAMBA_AD_MEMBER | Restore share root SELinux labels
  become: true
  become_user: root
  ansible.builtin.command:
    argv:
      - "{{ __samba_ad_member_restorecon }}"
      - -Rv
      - "{{ __samba_ad_member_directory.path }}"
  register: __samba_ad_member_relabel
  changed_when: "'Relabeled' in __samba_ad_member_relabel.stdout"
  listen: relabel shared directories
